home/urls.py
from django.urls import path

from home import views
from traveller import  views as tview
app_name='home'
urlpatterns=[
    path('',views.Index.as_view(),name='index'),
    path('saccos/',views.Saccos.as_view(),name='saccos'),
    path('book_ride/',views.book_ride,name='book-ride'),
    path('signin/',tview.log_user_in,name='signin'),
    path('signup/',tview.create_customer_account,name='signup'),
    path('logout/',views.logout_view,name='logout'),


   #validation ajax requests
    path('ajax/list_sacco/',views.check_saccos,name='check-saccos'),
    path('ajax/list_rides/', views.get_sacco_rides, name='listrides'),
    #path('ajax/get_ride_details/', views.get_ride_details, name='getridedetails'),
    path('ajax/get-active-fare/', views.getActivePrice, name='getactivefare'),
    path('ajax/ride_details/',views.get_ride_important_details,name='rideimportantdetails'),
    path('confirmation/',views.confirmation_url,name='confirmation'),
    path('validation/',views.validation_url,name='validation'),
    path('try-payments/',views.process_payment,name='mobile_payment'),

]

mat360/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    #path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('admin/',include('mat360admin.urls')),

    path('saccoManager/',include('sacco_manager.urls')),
    path('stageController/', include('stagecontroller.urls')),
    path('traveller/',include('traveller.urls')),
    path('driver/',include('driver.urls')),

    #api urls
    path('traveller/api/v1/',include('traveller.api.urls')),
]

traveller/api/urls.py
from django.urls import path
from traveller.api.views import travellerRegistrationView
app_name='traveller'

urlpatterns=[
    path('register',travellerRegistrationView,name='pi_register'),
]

traveller/urls.py
from django.urls import path

from traveller import views
from  home import views as home_view
app_name='traveller'

urlpatterns=[
  path('accounts/travellerdash/',views.load_traveller_dashboard,name='t-dash'),
  path('accounts/bookride/',views.home_book_ride,name='bookride'),
  path('accounts/myrides/',views.my_rides,name='myrides'),
  path('accounts/pay_ride',views.pay_your_ride,name='pay_ride'),

]

home/models.py
from django.db import models

# Create your models here.

traveller/models.py
from django.db import models

# Create your models here.

home/views.py
import json
from django.contrib.auth import logout

from django.core import serializers
from django.db.models import Q
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render, redirect
import requests
from requests.auth import HTTPBasicAuth
import africastalking


# Create your views here.
from django.views.generic import TemplateView

from mat360.settings import AFRICAS_TALKING_USERNAME, AFRICAS_TALKING_API_KEY
from sacco_manager.models import Vehicle, Sacco, Route, StageController
from stagecontroller.models import FareUpdate
from sacco_manager.algorithms.algo import FilterClass
from sacco_manager.algorithms.Universal import ValidationCheck

#Create Instance
validI=ValidationCheck()


class Index(TemplateView):
    template_name = 'landing.html'
class Saccos(TemplateView):
    template_name = 'travel_agency.html'
def book_ride(request):
    if request.method=='POST':
        request.session['vehicle_id']=request.POST['rideNumber']
        request.session['departure']=request.POST['departure']
        request.session['destination'] = request.POST['destination']
        return redirect('home:signin')
    return render(request,'book-ride.html',{'stations':validI.getallroutes()})
def process_login(request):
    return render(request,'signin.html')
def create_account(request):
    return render(request,'signup.html')

def check_saccos(request):
    departure =request.GET.get('departure', None)
    destination=request.GET.get('destination',None)

    #Final values to query
    d_departure=''
    d_destination=''

    filterI=FilterClass()

    if filterI.prepare_town_search(departure,destination):
        d_departure=departure.upper()
        d_destination=destination.upper()
    else:
        d_departure=destination.upper()
        d_destination=departure.upper()
    result_set=[]
    #all_saccos=Sacco.objects.all()
    all_saccos=Route.objects.filter(departure=d_departure).filter(destination=d_destination)
    for sacco in all_saccos:
        result_set.append({'name':sacco.sacco.sacco_name,'regnumber':sacco.sacco.sacco_reg_no})
    #data={'vehicle':serializers.serialize('json',)}
    return  HttpResponse(json.dumps(result_set),content_type='application/json')


def get_sacco_rides(request):
    sacoNo=request.GET.get('sacco',None)
    departure=request.GET.get('departure',None)
    destination = request.GET.get('destination', None)
    d_departure = ''
    d_destination = ''
    filterI = FilterClass()
    if filterI.prepare_town_search(departure, destination):
        d_departure = departure.upper()
        d_destination = destination.upper()
    else:
        d_departure = destination.upper()
        d_destination = departure.upper()
    sacco = Sacco.objects.get(sacco_reg_no=sacoNo)
    routeI=Route.objects.get(Q(departure=d_departure),Q(destination=d_destination),Q(sacco=sacco))
    result_set=[]
    #all_saccos=Sacco.objects.all()

    all_rides=Vehicle.objects.filter(sacco=sacco).filter(route=routeI).filter(vcontrol__station=departure.upper()).filter(vcontrol__controller_confirmation_status=True).filter(vehiclestatus__status=None)
    for ride in all_rides:
        result_set.append({'vnumber':ride.v_number})
    #data={'vehicle':serializers.serialize('json',)}
    return  HttpResponse(json.dumps(result_set),content_type='application/json')







#Get three properties of the selected ride,total_capacity,active_fare and active bookings.
def get_ride_important_details(request):
    #Values from front end.
    v_number=request.GET.get('vnumber',None)
    departure=request.GET.get('departure',None)
    destination = request.GET.get('destination', None)
    sacco_reg=request.GET.get('saccoreg', None)

    #Get the capacity.
    v_list=list(Vehicle.objects.filter(pk=v_number).values_list('capacity',flat=True))
    capacity=v_list[0]
    d_departure = ''
    d_destination = ''
    filterI = FilterClass()
    if filterI.prepare_town_search(departure, destination):
        d_departure = departure.upper()
        d_destination = destination.upper()
    else:
        d_departure = destination.upper()
        d_destination = departure.upper()
    #Get Route;
    sacco = Sacco.objects.get(pk=sacco_reg)
    routeI = Route.objects.get(Q(departure=d_departure), Q(destination=d_destination), Q(sacco=sacco))
    stagecontrolerI=StageController.objects.get(Q(station=departure.upper()),Q(sacco=sacco))
    fareI=FareUpdate.objects.filter(Q(route=routeI),Q(sacco=sacco),Q(stagecontroller=stagecontrolerI)).latest('created')
    fareAmount=str(fareI.amount)
    bookings=validI.get_bookings_per_ride(v_number)

    #Function to hold active bookings willcome here;
    v_details=[]
    v_details.append({'capacity':capacity,'fareamount':fareAmount,'tbookings':bookings})

    return HttpResponse(json.dumps(v_details), content_type='application/json')




def getActivePrice(request):
    #vehicle_no=request.GET.get('vnumber',None)
    sacco=request.GET.get('sacco',None)
    departureT=request.GET.get('departure',None)
    destinationT=request.GET.get('destination',None)
    routeI=Route.objects.get(Q(departure=departureT.upper()),Q(destination=destinationT.upper()))
    saccoI=Sacco.objects.get(sacco_name=sacco)
    result_set=[]

    try:
        fareUpdateI=FareUpdate.objects.filter(Q(route=routeI.id),Q(sacco=saccoI.id)).latest('created')
        result_set.append({'active_fare':fareUpdateI.amount})
    except FareUpdate.DoesNotExist:
        result_set.append({'active_fare': None})
    return HttpResponse(json.dumps(result_set), content_type='application/json')






def mpesaSimulate(request):
    #generaing access tokens;
    consumer_key = "hGIRSPOmGh4gQpggg9gUdQUP7TEob1yz"
    consumer_secret = "4iPmR7fPaxGYEwJ1"
    api_URL = "https://sandbox.safaricom.co.ke/oauth/v1/generate?grant_type=client_credentials"

    r = requests.get(api_URL, auth=HTTPBasicAuth(consumer_key, consumer_secret))
    myr=json.loads(r.text)
    access_token=myr["access_token"]
    api_url = "http://sandbox.safaricom.co.ke/mpesa/c2b/v1/registerurl"
    headers = {"Authorization": "Bearer %s" % access_token}
    request = {"ShortCode": "60502",
               "ResponseType": "Completed",
               "ConfirmationURL": "http://aa2e571b3b98.ngrok.io/confirmation/",
               "ValidationURL": "http://aa2e571b3b98.ngrok.io/validation/"}
    response = requests.post(api_url, json=request, headers=headers)
    return HttpResponse(response.text)

    #print(r.text)
def confirmation_url(request):
    myresponse={
          "ResultCode": 0,
          "ResultDesc": "Accepted"
        }
    return HttpResponse(json.dumps(myresponse), content_type='application/json')

def validation_url(request):
    confirmation_response={
        "C2BPaymentConfirmationResult": "Success"
    }
    return HttpResponse(json.dumps(confirmation_response), content_type='application/json')




#AFRICASTALKING PAYMENT

def process_payment(request):
    username="sandbox "
    api_key="31c118383e9d42b1cc179cd5d7fe413ace1e3e1b223264764fcd8ed705ff3213"
    africastalking.initialize(username, api_key)
    pay=africastalking.Payment

    product_name = "Travel"
    phone_number = "+254794249057"
    currency_code = "KES"
    amount = 250
    response={}

    try:
        response = pay.mobile_checkout(product_name, phone_number, currency_code, amount)
        print(response)
    except Exception as e:
        response=e
    return HttpResponse(response)




def logout_view(request):
    logout(request)
    return redirect('home:signin')

traveller/api/views.py
from rest_framework.decorators import api_view
from rest_framework.response import Response

from traveller.api.serializers import TravellerRegistrationSerializer

@api_view(['POST',])
def travellerRegistrationView(request):
    if request.method == 'POST':
        serializer=TravellerRegistrationSerializer(required=False,data=request.data)
        data=""
        if serializer.is_valid():
            account=serializer.save()
            data='You have Successfully registered as a new Traveller'
        else:
            response=serializer.errors
            data=response['username'][0]

        return Response(data)

traveller/views.py
import io
from django.http import FileResponse
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import make_password
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect

# Create your views here.
from django.views.generic import TemplateView

from mat360admin.models import Mat360SystemUsers,Payments
from mat360admin.core.payments import MpesaClient
from sacco_manager.algorithms.finances import FinancesSavingOperations
from sacco_manager.algorithms.travellerOR import TravellerOperations
from sacco_manager.models import Vehicle, VehicleBookings, VehicleStatus
from sacco_manager.algorithms.Universal import ValidationCheck
from django.views.decorators.csrf import csrf_exempt

''''
This will involve all views that are related to customers .
1.Registration of customers to the database.
2.Processing customer Login
3.Making bookings and paying fees using MPESA.
4.Display of customer receipts  and history of travel.
'''
validI=ValidationCheck()
mpesa_client=MpesaClient()
toperations=TravellerOperations()

def create_customer_account(request):
    if  request.method == 'POST':
        fname=request.POST['fname']
        lname = request.POST['lname']
        phone = request.POST['phone']
        password = request.POST['password']
        cpassword=request.POST['cpassword']

        if password !=cpassword:
            messages.error(request,'ERROR. Passwords do not match.')
        else:
            Mat360SystemUsers.objects.create(
                first_name=fname,
                last_name=lname,
                username=phone,
                password=make_password(password,salt=None),
                is_customer=True
            )
            messages.success(request,'Your account has been succesfully created. You can now login by clicking the link below.')






    return render(request,'signup.html',locals())


#Login the driver of the
def log_user_in(request):
    if request.method == 'POST':
        user=authenticate(username=request.POST['username'],password=request.POST['pass'])
        if user is not None:
            login(request, user)
            if user.is_superuser:
                return redirect('mat360admin:admin-dash')
            elif user.is_staff and user.is_saccomanager:
                return redirect('sacco_manager:sacco-manager-dashboard')
            elif user.is_stagecontroller:
                return redirect('stagecontroller:stagecontroller-dashboard')
            elif user.is_driver:
                return redirect('driver:index')

            elif user.is_customer:
                return redirect('traveller:t-dash')
                #process traveller.


        else:
            messages.error(request,'ERROR. You have entered wrong login credentials.')


    return render(request,'signin.html')

@login_required(login_url='home:signin')
def load_traveller_dashboard(request):
    total_expenses=toperations.getTotalTransportExpense(request.user)

    return  render(request,'traveller/home.html',{'t_expense':total_expenses})
@login_required(login_url='home:signin')
def home_book_ride(request):
    if request.method=='POST':
        request.session['vehicle_id']=request.POST['rideNumber']
        request.session['departure']=request.POST['departure']
        request.session['destination'] = request.POST['destination']
        request.session['saccoName'] = request.POST['saccoName']
        request.session['amount'] = request.POST['amount']
        return redirect('traveller:pay_ride')
    return render(request,'traveller/book_ride.html',{'stations':validI.getallroutes()})
@login_required(login_url='home:signin')
@csrf_exempt
def pay_your_ride(request):
    response=""
    if request.method == 'POST':
        vnumber=request.session.get('vehicle_id')
        confirmation_code=request.POST['c_code']
        vehicleI=Vehicle.objects.get(pk=vnumber)
        user=Mat360SystemUsers.objects.get(username=request.user.username)
        if validI.prevent_double_booking(user,vehicleI,confirmation_code):
            messages.error(request,"OOPS! .You cannot make another booking because you already have an active booking.")
        else:
            #Confirm is the payment is successful
            if(Payments.objects.filter(booking_code=confirmation_code).filter(bill_refnumber=vehicleI).filter(user=request.user).exists()):
                #Update the payment status to be true
                VehicleBookings.objects.filter(booking_code=confirmation_code).filter(vehicle=vehicleI).filter(traveller=request.user).update(payment_status=True)
                messages.success(request,"Your booking was successful.Kindly maintain a considerable distance from stage.You will get an sms when your ride is ready to leave stage.")            
            else:                
                messages.error(request,"Wrong Business confirmation code")


        #Check if the number of bookings is equivalent to the maximum capacity.
        if validI.get_bookings_per_ride(vnumber) == int(vehicleI.capacity):
            VehicleStatus.objects.create(vehicle=vehicleI,status='full')
            #We send sms to every member;
            all_users=VehicleBookings.objects.filter(vehicle=vehicleI)
            for user in all_users:
                response=validI.sendSms(user.traveller.username,user.traveller.first_name,user.traveller.last_name)


        #Save the details to database now.
    return render(request,'traveller/pay_ride.html',{'v_number':request.session.get('vehicle_id'),'sacco_name':request.session.get('saccoName'),'amount':request.session.get('amount'),'departure':request.session.get('departure'),'destination':request.session.get('destination'),'response':response})

@login_required(login_url='home:signin')
def my_rides(request):
    tvOps=TravellerOperations()
    user = Mat360SystemUsers.objects.get(username=request.user.username)
    all_rides=tvOps.get_my_rides(user)
    return  render(request,'traveller/my_rides.html',{'all_rides':all_rides})

templates/traveller/book_ride.html
{% extends 'traveller/traveller_base.html' %}
{% block content %}
<div id="main">
       <div class="container">
        <div class="row">
       <div class="col s12 m6 offset-m3">
           <div class="card">
               <div class="card-content">
                   <div class="row">
                       <div class="col s12 m12">
                           <h6 class="center-align purple-text">FILL YOUR RIDE DETAILS BELOW</h6>
                       </div>
                   </div>
                   <!--ROW2-->
                   <form method="post" action="">
                       {% csrf_token %}
                   <div class="row">
                       <div class="input-field col s12 m6">
                            <select class="browser-default" id="departure" name="departure">
                            <option value="" disabled selected>SELECT DEPARTING STATION</option>
                                {% for station in stations %}
                                     <option value="{{ station }}">{{ station }}</option>
                                {% endfor %}
                          </select>
                       </div>
                       <div class="input-field col s12 m6">
                            <select class="browser-default" id="destination" name="destination">
                            <option value="" disabled selected>SELECT DESTINATION STATION</option>
                                {% for station in stations %}
                                     <option value="{{ station }}">{{ station }}</option>
                                {% endfor %}
                          </select>

                       </div>
                   </div>

                   <!--ROW3-->
                   <div class="row">
                       <div class="input-field col s12 m6">
                           <select class="browser-default" id="saccoName" name="saccoName" >
                            <option value="" disabled selected>CHOOSE SACCO</option>
                          </select>

                       </div>
                       <div class="input-field col s12 m6">
                            <select class="browser-default" id="rideNumber" name="rideNumber">
                            <option value="" disabled selected>CHOOSE VEHICLE NUMBER</option>
                          </select>
                       </div>
                   </div>

                    <!--ROW4-->
                   <div class="row">
                       <div class="input-field col s12 m6">
                           <input type="text" placeholder="VEHICLE CAPACITY" class="validate" required id="totalSeats" name="totalSeats">
                       </div>
                       <div class="input-field col s12 m6">
                           <input type="text" placeholder="ACTIVE FARE" class="validate" required id="activeFare" name="amount">
                       </div>
                   </div>
                    <!--ROW5-->
                   <div class="row">
                       <div class="input-field col s12 m6">
                           <input type="text" placeholder="ACTIVE BOOKINGS" class="validate"  required id="activeBookings"  name="activeBookings">
                       </div>

                   </div>
                    <!--ROW5-->
                   <div class="row">
                       <div class="input-field col s12 m6 offset-m3">
                           <button type="submit" class="btn btn-block mat360-btn">Pay Your Ride</button>
                       </div>

                   </div>

                       </form>

               </div>
           </div>
       </div>
    </div>
       <!--At Home Page End-->
       </div>
</div>


    <!--JAVASCRIPT-->
   {% block javascript %}
   <script>
           $(document).ready(function () {
               //Detect change in the destination
               $('#destination').change(function () {

              var departure = $("#departure").val();
              var destination = $(this).val();
             if (departure == ''){
                 alert('Please fill in your departure Town to Proceed')
             }
             else {
                  $.ajax({
                     url:"{% url 'home:check-saccos' %}",
                     data:{
                         'departure':departure,
                         'destination':destination,
                     },
                     dataType: 'json',
                     success:function (result) {
                         $("#saccoName option").remove();
                             InitName='CHOOSE SACCO';
                             InitValue='NULL';
                             $("#saccoName").append(new Option(InitName,InitValue));

                         for (var i = result.length - 1; i >= 0; i--) {
                             saccoName=result[i].name;
                             saccoRegNo=result[i].regnumber;
                             $("#saccoName").append(new Option(saccoName,saccoRegNo));
                                    //$("#saccoName").append('<option >'+ result[i].name +'</option>');
                                };


                     },

                 })
             }










        })
               //Detect change in the value of Sacco to list all the rides;
               //This is the function to detect on change in the select of saccos.
         $('#saccoName').change(function () {
               var sacco=$(this).children("option:selected").val();
              var departure = $("#departure").val();
              var destination = $("#destination").val();
             $.ajax({
                 url:"{% url 'home:listrides' %}",
                 data:{
                     'sacco':sacco,
                     'departure':departure,
                     'destination':destination,
                 },
                 dataType: 'json',
                 success:function (result) {
                     $("#rideNumber option").remove();
                             InitName='CHOOSE VEHICLE NUMBER';
                             InitValue='NULL';
                             $("#rideNumber").append(new Option(InitName,InitValue));
                     for (var i = result.length - 1; i >= 0; i--) {
                                vehicleNumber=result[i].vnumber
                                $("#rideNumber").append(new Option(vehicleNumber,vehicleNumber));
                            };


                 }

             })       });
               //On focus of the sacco name
                 $('#saccoName').click(function () {

              var departure = $("#departure").val();
              var destination = $("#destination").val();
                  $.ajax({
                     url:"{% url 'home:check-saccos' %}",
                     data:{
                         'departure':departure,
                         'destination':destination,
                     },
                     dataType: 'json',
                     success:function (result) {
                         if(result.length<1){
                             alert("SORRY. There is no sacco registered in our platform operating in the specified route.")

                         }





                     },

                 })











        })
               //This is function to fill vehicle details
                $('#rideNumber').change(function () {
             var departure = $("#departure").val();
             var destination = $("#destination").val();
             var ride=$(this).children("option:selected").val()
              var sacco=$("#saccoName").children("option:selected").val()

             $.ajax({
                 url:"{% url 'home:rideimportantdetails' %}",
                 data:{
                     'saccoreg':sacco,
                     'vnumber':ride,
                     'departure':departure,
                     'destination':destination,
                 },
                 dataType: 'json',
                 success:function (result) {
                      $("#totalSeats").val(result[0].capacity);
                      $("#activeFare").val(result[0].fareamount);
                      $("#activeBookings").val(result[0].tbookings);

                      //alert(JSON.stringify(result))

                 }

             })       });

           })
        </script>
{% endblock %}
{% endblock %}

templates/traveller/traveller_base.html
<!DOCTYPE html>
<html class="loading" lang="en" data-textdirection="ltr">
  <!-- BEGIN: Head-->
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
    <meta name="description" content="Materialize is a Material Design Admin Template,It's modern, responsive and based on Material Design by Google.">
    <meta name="keywords" content="materialize, admin template, dashboard template, flat admin template, responsive admin template, eCommerce dashboard, analytic dashboard">
    <meta name="author" content="ThemeSelect">

      {% load static %}
    <title>Mat360|Public transportation now at the palm of your hand</title>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- BEGIN: VENDOR CSS-->
    <link rel="stylesheet" type="text/css" href="{% static 'controlled/css/vendors.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'controlled/css/animate.css' %}">
    <!-- END: VENDOR CSS-->
    <!-- BEGIN: Page Level CSS-->
    <link rel="stylesheet" type="text/css" href="{% static 'controlled/css/materialize.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'controlled/css/style.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'controlled/css/dashboard-modern.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'controlled/css/intro.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'controlled/css/main.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/new-main.css' %}">
    <link rel="shortcut icon" href="{% static 'assets/media/logo.ico' %}" type="image/x-icon"/>



  </head>
  <!-- END: Head-->
  <body class="vertical-layout vertical-menu-collapsible page-header-dark vertical-modern-menu preload-transitions 2-columns   " data-open="click" data-menu="vertical-modern-menu" data-col="2-columns">

    <!-- BEGIN: Header-->
    <header class="page-topbar" id="header">
      <div class="navbar navbar-fixed">
        <nav class="navbar-main navbar-color nav-collapsible sideNav-lock navbar-dark gradient-45deg-indigo-purple no-shadow">
          <div class="nav-wrapper">
            <ul class="navbar-list right">
              <li><a class="waves-effect waves-block waves-light profile-button" href="javascript:void(0);" data-target="profile-dropdown">{{ user.first_name }}<span>

              </span><span class="material-icons">keyboard_arrow_down</span> </a></li>

            </ul>


            <ul class="dropdown-content" id="profile-dropdown">
                <li><a class="grey-text text-darken-1" href=""><i class="material-icons">person_outline</i> Profile</a></li>
                <li class="divider"></li>
                <li><a class="grey-text text-darken-1" href="{% url 'home:logout' %}"><i class="material-icons">keyboard_tab</i> Logout</a></li>
            </ul>
          </div>
        </nav>
      </div>
    </header>
    <!-- END: Header-->

    <aside class="sidenav-main nav-expanded nav-lock nav-collapsible sidenav-light sidenav-active-square">
      <div class="brand-sidebar">
               <p class="center-align">Welcome {{ request.user.first_name }}</p>
      </div>
      <ul class="sidenav sidenav-collapsible leftside-navigation collapsible sidenav-fixed menu-shadow" id="slide-out" data-menu="menu-navigation" data-collapsible="menu-accordion">

         <li class="bold"><a class="waves-effect waves-cyan " href="{% url 'traveller:t-dash' %}"><i class="material-icons">home</i><span class="menu-title" data-i18n="User Profile">Home</span></a></li>
         <li class="bold"><a class="waves-effect waves-cyan " href="{% url 'traveller:bookride' %}"><i class="material-icons">assignment</i><span class="menu-title" data-i18n="User Profile">Book a Ride</span></a></li>
         <li class="bold"><a class="waves-effect waves-cyan " href="{% url 'traveller:myrides' %}"><i class="material-icons">fact_check</i><span class="menu-title" data-i18n="User Profile">My Rides</span></a></li>
         

      </ul>
      <div class="navigation-background"></div><a class="sidenav-trigger btn-sidenav-toggle btn-floating btn-medium waves-effect waves-light hide-on-large-only" href="#" data-target="slide-out"><i class="material-icons">menu</i></a>
    </aside>
    <!-- END: SideNav-->








    <!-- BEGIN: Page Main-->


        {% block content %}

        {% endblock %}







    <!-- END: Page Main-->












    <!-- BEGIN: Footer-->

    <footer class="page-footer footer footer-static footer-dark gradient-45deg-indigo-purple gradient-shadow navbar-border navbar-shadow">
      <div class="footer-copyright">
        <div class="container"><span>&copy; 2020 <a href="" target="_blank">Mat360</a> All rights reserved.</span><span class="right hide-on-small-only">Design and Developed by <a href="hornafrictech.com">HornAfricTech</a></span></div>
      </div>
    </footer>

    <!--JQUERY-->
<script  src="https://code.jquery.com/jquery-3.5.1.min.js"  integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="  crossorigin="anonymous"></script>
    <!-- Compiled and minified JavaScript -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <!-- BEGIN VENDOR JS-->
    <script src="{% static 'controlled/js/vendors.min.js' %}"></script>
    <!-- BEGIN VENDOR JS-->
    <!-- BEGIN PAGE VENDOR JS-->
    <script src="{% static 'controlled/jss/chart.min.js' %}"></script>
    <!-- BEGIN THEME  JS-->
    <script src="{% static 'controlled/js/plugins.min.js' %}"></script>
    <script src="{% static 'controlled/js/search.min.js' %}"></script>
    <script src="{% static 'controlled/js/customizer.min.js' %}"></script>
    <!-- END THEME  JS-->
    <!-- BEGIN PAGE LEVEL JS-->
    <script src="{% static 'controlled/js/dashboard-modern.js' %}"></script>
    <script src="{% static 'controlled/js/intro.min.js' %}"></script>
    <!-- END PAGE LEVEL JS-->
  {% block javascript %}
  {% endblock %}
  </body>
</html>