home/urls.py
from django.urls import path

from home import views
from traveller import  views as tview
app_name='home'
urlpatterns=[
    path('',views.Index.as_view(),name='index'),
    path('saccos/',views.Saccos.as_view(),name='saccos'),
    path('book_ride/',views.book_ride,name='book-ride'),
    path('signin/',tview.log_user_in,name='signin'),
    path('signup/',tview.create_customer_account,name='signup'),
    path('logout/',views.logout_view,name='logout'),


   #validation ajax requests
    path('ajax/list_sacco/',views.check_saccos,name='check-saccos'),
    path('ajax/list_rides/', views.get_sacco_rides, name='listrides'),
    #path('ajax/get_ride_details/', views.get_ride_details, name='getridedetails'),
    path('ajax/get-active-fare/', views.getActivePrice, name='getactivefare'),
    path('ajax/ride_details/',views.get_ride_important_details,name='rideimportantdetails'),
    path('confirmation/',views.confirmation_url,name='confirmation'),
    path('validation/',views.validation_url,name='validation'),
    path('try-payments/',views.process_payment,name='mobile_payment'),

]

mat360/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    #path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('admin/',include('mat360admin.urls')),

    path('saccoManager/',include('sacco_manager.urls')),
    path('stageController/', include('stagecontroller.urls')),
    path('traveller/',include('traveller.urls')),
    path('driver/',include('driver.urls')),

    #api urls
    path('traveller/api/v1/',include('traveller.api.urls')),
]

mat360admin/urls.py
from django.urls import path

from mat360admin import views
app_name='mat360admin'

urlpatterns=[
    path('',views.log_admin_in,name='admin-login'),
    path('accounts/',views.load_admin_dash,name='admin-dash'),
    path('create-admin/',views.create_system_admin,name='create-admin'),
    path('all_transactions',views.getFareTransactions,name='all_transactions'),
    path('c2b/register',views.register_urls,name='register_mpesa_validation'),
    path('c2b/confirmation',views.confirmation,name='confirmation'),
    path('c2b/validation',views.validation,name='validation'),
    path('c2b/simulate',views.simulatec2b,name='simulate'),
    path('c2b/lipanampesa',views.lipaNaMpesaOnline,name='lipanampesa'),
    path('admin/accounts/sacco_requests_applications/',views.view_sacco_requests_applications_and_approve,name='admin-sacco-application-requests'),
    path('admin/accounts/approved_applications/',views.ApprovedSaccoRequests.as_view(),name='approved_sacco_requests'),

]

sacco_manager/urls.py
from django.urls import path
from sacco_manager import views

app_name='sacco_manager'

urlpatterns=[
    path('request_sacco_registration/',views.save_sacco_registration_requests,name='request-sacco-registration'),
    path('accounts/',views.sacco_manager_dashboard,name='sacco-manager-dashboard'),
    path('accounts/new_vehicle',views.new_vehicle_registration,name='new-vehicle-registration'),
    path('accounts/our_fleet',views.get_fleet,name='our-fleet'),
    path('accounts/new_stage_controller', views.register_stage_controller, name='new-controller'),
    path('accounts/our_settings', views.sacco_settings, name="sacco-settings"),
    path('accounts/vehicle_statistics',views.vehicle_statistics,name='vehicle_stats'),
    #path('accounts/route-management/',views.route_management_home,name='route_management'),
    #Company Finances
    path('accounts/sacco_finances/',views.SaccoFinancesPage.as_view(),name='sacco-finances'),
    path('accounts/sacco_finances/current_balance_distribution',views.CurrentBalanceDistribution.as_view(),name='sacco-current-balance'),
    path('accounts/route-management/register_route', views.register_vehicle_route, name='register_route'),
    #Ajax Based Functons
    path('accounts/ajax/VehicleStats/',views.getVehicleStatistics,name='ajax-vehicle-stats'),
    path('',views.logout_view,name='logout'),
]

home/models.py
from django.db import models

# Create your models here.

mat360admin/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models




class Mat360SystemUsers(AbstractUser):
    is_customer=models.BooleanField(default=False)
    is_driver=models.BooleanField(default=False)
    is_saccomanager=models.BooleanField(default=False)
    is_stagecontroller=models.BooleanField(default=False)


    class Meta:
        db_table='mat360systemusers'
'''
This is the table to hold the payments of the MPESA Transactions.
'''
class Payments(models.Model):
    #This will help us get the number of the user paying.
    user=models.ForeignKey(Mat360SystemUsers,on_delete=models.CASCADE)
    transaction_type=models.CharField(max_length=10,blank=False,null=False)
    transaction_id=models.CharField(max_length=10,blank=False,unique=True)
    transaction_time=models.DateTimeField()
    transaction_amount=models.DecimalField(max_digits=10,decimal_places=2)
    business_shortcode=models.CharField(max_length=6,blank=False,null=False)
    bill_refnumber=models.ForeignKey("sacco_manager.Vehicle",on_delete=models.CASCADE)
    invoice_number=models.CharField(max_length=5,null=True,blank=True)
    msisdn=models.CharField(max_length=12,blank=False,null=False)
    first_name=models.CharField(max_length=20,blank=False,null=False)
    middle_name=models.CharField(max_length=20,blank=True,null=True)
    last_name=models.CharField(max_length=20,blank=False,null=False)
    booking_code=models.PositiveIntegerField()

    class Meta:
        db_table="ride_payments"

    
        

sacco_manager/forms.py
from django import forms
from mat360admin.models import Mat360SystemUsers
from sacco_manager.models import SaccoRegistrationRequests, Vehicle


class SaccoRequestRegistrationForm(forms.ModelForm):
    class Meta:
        model = SaccoRegistrationRequests
        fields = ('first_name','last_name','id_number','email_address','phone_number','sacco_reg_no','sacco_name')
class VehicleRegistrationForm(forms.ModelForm):
    #Driver_details
    first_name = forms.CharField(max_length=40, required=True, widget=forms.TextInput())
    last_name = forms.CharField(max_length=40, required=True, widget=forms.TextInput())

    id_number = forms.CharField(max_length=8, required=True, widget=forms.TextInput())

    phone_number = forms.CharField(max_length=100, required=True, widget=forms.TextInput())
    email_address = forms.CharField(max_length=100, required=True, widget=forms.TextInput())

    class Meta:
        model=Vehicle
        fields = ('v_number', 'capacity','first_name','last_name','id_number','phone_number','email_address')
class StageControllerRegistrationForm(forms.ModelForm):
    id_number=forms.CharField(max_length=8,required=True,widget=forms.TextInput())
    station = forms.CharField(max_length=40, required=True, widget=forms.TextInput())
    phone_number = forms.CharField(max_length=10, required=True, widget=forms.TextInput())


    class Meta:
        model=Mat360SystemUsers
        fields = ('first_name', 'last_name','email','id_number','phone_number','station')

home/views.py
import json
from django.contrib.auth import logout

from django.core import serializers
from django.db.models import Q
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render, redirect
import requests
from requests.auth import HTTPBasicAuth
import africastalking


# Create your views here.
from django.views.generic import TemplateView

from mat360.settings import AFRICAS_TALKING_USERNAME, AFRICAS_TALKING_API_KEY
from sacco_manager.models import Vehicle, Sacco, Route, StageController
from stagecontroller.models import FareUpdate
from sacco_manager.algorithms.algo import FilterClass
from sacco_manager.algorithms.Universal import ValidationCheck

#Create Instance
validI=ValidationCheck()


class Index(TemplateView):
    template_name = 'landing.html'
class Saccos(TemplateView):
    template_name = 'travel_agency.html'
def book_ride(request):
    if request.method=='POST':
        request.session['vehicle_id']=request.POST['rideNumber']
        request.session['departure']=request.POST['departure']
        request.session['destination'] = request.POST['destination']
        return redirect('home:signin')
    return render(request,'book-ride.html',{'stations':validI.getallroutes()})
def process_login(request):
    return render(request,'signin.html')
def create_account(request):
    return render(request,'signup.html')

def check_saccos(request):
    departure =request.GET.get('departure', None)
    destination=request.GET.get('destination',None)

    #Final values to query
    d_departure=''
    d_destination=''

    filterI=FilterClass()

    if filterI.prepare_town_search(departure,destination):
        d_departure=departure.upper()
        d_destination=destination.upper()
    else:
        d_departure=destination.upper()
        d_destination=departure.upper()
    result_set=[]
    #all_saccos=Sacco.objects.all()
    all_saccos=Route.objects.filter(departure=d_departure).filter(destination=d_destination)
    for sacco in all_saccos:
        result_set.append({'name':sacco.sacco.sacco_name,'regnumber':sacco.sacco.sacco_reg_no})
    #data={'vehicle':serializers.serialize('json',)}
    return  HttpResponse(json.dumps(result_set),content_type='application/json')


def get_sacco_rides(request):
    sacoNo=request.GET.get('sacco',None)
    departure=request.GET.get('departure',None)
    destination = request.GET.get('destination', None)
    d_departure = ''
    d_destination = ''
    filterI = FilterClass()
    if filterI.prepare_town_search(departure, destination):
        d_departure = departure.upper()
        d_destination = destination.upper()
    else:
        d_departure = destination.upper()
        d_destination = departure.upper()
    sacco = Sacco.objects.get(sacco_reg_no=sacoNo)
    routeI=Route.objects.get(Q(departure=d_departure),Q(destination=d_destination),Q(sacco=sacco))
    result_set=[]
    #all_saccos=Sacco.objects.all()

    all_rides=Vehicle.objects.filter(sacco=sacco).filter(route=routeI).filter(vcontrol__station=departure.upper()).filter(vcontrol__controller_confirmation_status=True).filter(vehiclestatus__status=None)
    for ride in all_rides:
        result_set.append({'vnumber':ride.v_number})
    #data={'vehicle':serializers.serialize('json',)}
    return  HttpResponse(json.dumps(result_set),content_type='application/json')







#Get three properties of the selected ride,total_capacity,active_fare and active bookings.
def get_ride_important_details(request):
    #Values from front end.
    v_number=request.GET.get('vnumber',None)
    departure=request.GET.get('departure',None)
    destination = request.GET.get('destination', None)
    sacco_reg=request.GET.get('saccoreg', None)

    #Get the capacity.
    v_list=list(Vehicle.objects.filter(pk=v_number).values_list('capacity',flat=True))
    capacity=v_list[0]
    d_departure = ''
    d_destination = ''
    filterI = FilterClass()
    if filterI.prepare_town_search(departure, destination):
        d_departure = departure.upper()
        d_destination = destination.upper()
    else:
        d_departure = destination.upper()
        d_destination = departure.upper()
    #Get Route;
    sacco = Sacco.objects.get(pk=sacco_reg)
    routeI = Route.objects.get(Q(departure=d_departure), Q(destination=d_destination), Q(sacco=sacco))
    stagecontrolerI=StageController.objects.get(Q(station=departure.upper()),Q(sacco=sacco))
    fareI=FareUpdate.objects.filter(Q(route=routeI),Q(sacco=sacco),Q(stagecontroller=stagecontrolerI)).latest('created')
    fareAmount=str(fareI.amount)
    bookings=validI.get_bookings_per_ride(v_number)

    #Function to hold active bookings willcome here;
    v_details=[]
    v_details.append({'capacity':capacity,'fareamount':fareAmount,'tbookings':bookings})

    return HttpResponse(json.dumps(v_details), content_type='application/json')




def getActivePrice(request):
    #vehicle_no=request.GET.get('vnumber',None)
    sacco=request.GET.get('sacco',None)
    departureT=request.GET.get('departure',None)
    destinationT=request.GET.get('destination',None)
    routeI=Route.objects.get(Q(departure=departureT.upper()),Q(destination=destinationT.upper()))
    saccoI=Sacco.objects.get(sacco_name=sacco)
    result_set=[]

    try:
        fareUpdateI=FareUpdate.objects.filter(Q(route=routeI.id),Q(sacco=saccoI.id)).latest('created')
        result_set.append({'active_fare':fareUpdateI.amount})
    except FareUpdate.DoesNotExist:
        result_set.append({'active_fare': None})
    return HttpResponse(json.dumps(result_set), content_type='application/json')






def mpesaSimulate(request):
    #generaing access tokens;
    consumer_key = "hGIRSPOmGh4gQpggg9gUdQUP7TEob1yz"
    consumer_secret = "4iPmR7fPaxGYEwJ1"
    api_URL = "https://sandbox.safaricom.co.ke/oauth/v1/generate?grant_type=client_credentials"

    r = requests.get(api_URL, auth=HTTPBasicAuth(consumer_key, consumer_secret))
    myr=json.loads(r.text)
    access_token=myr["access_token"]
    api_url = "http://sandbox.safaricom.co.ke/mpesa/c2b/v1/registerurl"
    headers = {"Authorization": "Bearer %s" % access_token}
    request = {"ShortCode": "60502",
               "ResponseType": "Completed",
               "ConfirmationURL": "http://aa2e571b3b98.ngrok.io/confirmation/",
               "ValidationURL": "http://aa2e571b3b98.ngrok.io/validation/"}
    response = requests.post(api_url, json=request, headers=headers)
    return HttpResponse(response.text)

    #print(r.text)
def confirmation_url(request):
    myresponse={
          "ResultCode": 0,
          "ResultDesc": "Accepted"
        }
    return HttpResponse(json.dumps(myresponse), content_type='application/json')

def validation_url(request):
    confirmation_response={
        "C2BPaymentConfirmationResult": "Success"
    }
    return HttpResponse(json.dumps(confirmation_response), content_type='application/json')




#AFRICASTALKING PAYMENT

def process_payment(request):
    username="sandbox "
    api_key="31c118383e9d42b1cc179cd5d7fe413ace1e3e1b223264764fcd8ed705ff3213"
    africastalking.initialize(username, api_key)
    pay=africastalking.Payment

    product_name = "Travel"
    phone_number = "+254794249057"
    currency_code = "KES"
    amount = 250
    response={}

    try:
        response = pay.mobile_checkout(product_name, phone_number, currency_code, amount)
        print(response)
    except Exception as e:
        response=e
    return HttpResponse(response)




def logout_view(request):
    logout(request)
    return redirect('home:signin')

templates/index.html
<!DOCTYPE html>
<html>
<head>
	<title>Mat360</title>
	{% load static %}
	   <!--Let browser know website is optimized for mobile-->
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
 <!--Link to material Icons-->
 <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

       <!--Custom Css-->
   <link type="text/css" rel="stylesheet" href="{% static 'assets/css/style.css' %}"  media="screen,projection"/>


    </head>
</head>
<body>
	<header>
		<div class="container">
			<div class="row">
				<div class="col xl2 l2 m3 s5">
					<div class="logo">
						<a href="#!"><img src="{% static 'assets/media/logo.png' %}"></a>
					</div>
				</div>

				<div class="col xl10 l10 m9 s7">
					<div class="mainmenu">
						<ul>
							<li><a href="{% url 'home:index' %}" class="active"><i class="material-icons left icon">home</i>Home</a></li>
							<li><a href="{% url 'home:saccos' %}"><i class="material-icons left icon">groups</i>Sacco</a></li>
							<li><a href="{% url 'home:book-ride' %}"><i class="material-icons left icon">departure_board</i>Ride</a></li>
							<li><a href="{% url 'home:signup' %}"><i class="material-icons left icon">person_pin</i>Join US</a></li>
							<li><a href="{% url 'home:signin' %}"><i class="material-icons left icon">lock</i>Log In</a></li>							
						</ul>
					</div>
					<div class="mobilemenu">
						<span onclick="openNav()">&#9776;</span>
						<div id="mySidenav" class="sidemenu">
							<a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
							<ul>
							<li><a href="{% url 'home:index' %}"><i class="material-icons left icon">home</i>Home</a></li>
							<li><a href="{% url 'home:saccos' %}"><i class="material-icons left icon">groups</i>Sacco</a></li>
							<li><a href="{% url 'home:book-ride' %}"><i class="material-icons left icon">departure_board</i>Ride</a></li>
							<li><a href="{% url 'home:signup' %}"><i class="material-icons left icon">person_pin</i>Register</a></li>
							<li><a href="{% url 'home:signin' %}"><i class="material-icons left icon">lock</i>Log In</a></li>							
						</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
	</header>
	{% block content %}
	<section class="banner">
		<div class="container">
			<div class="banner-description">
				<div class="banner-content">					
					<h2>
						We Focus on making your Ride Comfortable,Safe and Secure on your favorite Sacco.
					</h2>
					<p>
						As a traveller we know you need time to focus on other important things. As a Sacco we know you need a better financial, fleet and customer management tool. We are giving you that and thus allow us to do the management for you.
					</p>
					<a href="{% url 'home:book-ride' %}" class="filterbtn" style="border-radius: 24px;color: white;background-color: #29465B;display: inline-block;padding: 2%">Book Ride Today</a>
				</div>
			</div>
		</div>
		
	</section>
	<section class="Whyus">
		<div class="container">
			<!--The First Row-->
			<div class="row">				
				<div class="col s12 m8">
					<h2>We Guarantee Safety</h2>
					<p>Booking is done at the comfort of your comfort zone. During this time of COVID-19 pandemic, we are giving you a solution to guarantee you social distance and prevent the spread of the virus.</p>
				</div>
			</div>

			<!--The First Row-->
			<div class="row">
				<div class="col s12 m8">
					<h2>Heartwarming Ride</h2>
					<p>With over 100 registered travel saccos registered on the platform, comfort ride is what is guaranteed. You can always select your favorite sacco.</p>
				</div>
				<div class="col s12 m4">
					<img src="{% static 'assets/media/safety.jpg' %}">
				</div>
				
			</div>
			<!--The First Row-->
			<div class="row">				
				<div class="col s12 m8">
					<h2>We are Cashless</h2>
					<p>Fare payment is always done through MPESA,DEBIT Card, Credit Card, T-Kash or Airtel money.Paypal is also another international accepted payment method for fare.This ensures convenience since no withdrawal charges and safety of cash. Besides that we are striving to reduce the spread of COVID-19 during this time of pandemic.</p>
				</div>
				
				
			</div>
			
		</div>
	</section>
	
	{% endblock %}



<!--JQUERY CDN Link-->
<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
 <!-- Compiled and minified JavaScript -->
 <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  <script type="text/javascript">
  	function openNav(){
  		document.getElementById("mySidenav").style.width="100%";
  	}
  	function closeNav(){
  		document.getElementById("mySidenav").style.width="0";
  	}
  </script>
{% block javascript %}
{% endblock %}    
</body>
</html>

templates/nav.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Mat360 | </title>
    {% load static %}
    <!-- Compiled and minified CSS -->
     <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" href="{% static 'assets/css/new-main.css' %}">
     <!--Let browser know website is optimized for mobile-->
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link rel="shortcut icon" href="{% static 'assets/media/logo.ico' %}" type="image/x-icon"/>
    <style>

    </style>
</head>
<body class="container-fluid">
<header>
 <div class="navbar-fixed">
 <nav style="background: white">
    <div class="nav-wrapper">
      <a href="{% url 'home:index' %}" class="brand-logo"><img src="{% static 'assets/media/logo.png' %}" height="55" ></a>
      <a href="#"  data-target="mobile-demo" class="sidenav-trigger customnav"><i class="material-icons">menu</i></a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">

        <li><a href="{% url 'mat360admin:create-admin' %}"><i class="material-icons left icon">departure_board</i>Admin</a></li>
        <li><a href="{% url 'home:saccos' %}"><i class="material-icons left icon">departure_board</i>Saccos</a></li>
        <li><a href="{% url 'home:book-ride' %}"><i class="material-icons left icon">departure_board</i>Book A Ride</a></li>
        <li><a href="{% url 'home:signup' %}"><i class="material-icons left icon">person_pin</i>Register</a></li>
        <li><a href="{% url 'home:signin' %}"><i class="material-icons left icon">lock</i>Sign In</a></li>
      </ul>
    </div>
  </nav>
 </div>
 <ul class="sidenav customStyle" id="mobile-demo">

        <li><a href="{% url 'home:saccos' %}"><i class="material-icons left icon">departure_board</i>Saccos</a></li>
        <li><a href="{% url 'home:book-ride' %}"><i class="material-icons left icon">departure_board</i>Book A Ride</a></li>
        <li><a href="{% url 'home:signup' %}"><i class="material-icons left icon">person_pin</i>Register</a></li>
        <li><a href="{% url 'home:signin' %}"><i class="material-icons left icon">lock</i>Sign In</a></li>
  </ul>
</header>
<main>
 <div id="main">
 {% block content %}
 {% endblock %}
 </div>
</main>
<footer class="page-footer customFooter">
          <div class="container">
            <div class="row">
              <div class="col l4 m4 s12">
                <h5 class="purple-text">What's New</h5>
                <p class="purple-text text-lighten-1">Nothing New</p>
              </div>
              <div class="col m4 l3 s12">
                <h5 class="purple-text">SACCOS</h5>
                <ul>
                  <li><a class="purple-text text-lighten-1" href="#!">Request Registration</a></li>
                  <li><a class="purple-text text-lighten-1" href="#!">ALL SACCOS</a></li>
                </ul>
              </div>
                <div class="col m4 l3 s12">
                <h5 class="purple-text">CONTACT US</h5>
                <ul>
                  <li><a class="purple-text text-lighten-1" href="#!"><i class="material-icons ">facebook</i> </a></li>
                  <li><a class="purple-text text-lighten-1" href="#!"><i class="material-icons left">phone_in_talk</i> +254794249057</a></li>

                </ul>
              </div>

            </div>
          </div>
          <div class="footer-copyright">
            <div class="container">
                <p class="center-align purple-text">© <script>document.write(new Date().getFullYear())</script> HornAfricTechnologies Limited</p>

            </div>
          </div>
        </footer>


<!--JQUERY-->
<script  src="https://code.jquery.com/jquery-3.5.1.min.js"  integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="  crossorigin="anonymous"></script>
    <!-- Compiled and minified JavaScript -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
<script>
    $(document).ready(function(){
    $('.sidenav').sidenav();
  });
</script>
{% block javascript %}
{% endblock %}
</body>
</html>

templates/new_sacco_registration_request.html
 <!DOCTYPE html>
  <html>
    <head>
        {% load static %}
      <!--Import Google Icon Font-->
      <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
         <link rel="stylesheet" href="{% static 'assets/css/new-main.css' %}">
          <link rel="shortcut icon" href="{% static 'assets/media/logo.ico' %}" type="image/x-icon"/>


      <!--Let browser know website is optimized for mobile-->
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    </head>

    <body class="container" id="main">
    <div class="row">
        <form class="card col s12 m8 offset-m2" method="post" enctype="multipart/form-data" action="">
            {% csrf_token %}


            <div class="card-content">
           <span class="card-title purple-text center-align">NEW SACCO REGISTRATION REQUEST FORM</span>
                <div class="divider"></div>
                <p class="center-align pink-text">This is only used by sacco managers with registration certificates</p>
                {% if messages %}
                    {% for message in messages %}
                        <p class="center-align">{{ message }}</p>
                    {% endfor %}
                {% endif %}
                <div class="row">
                    <div class="input-field col s12 m6">
                       {{ form.first_name }}
                        <label for="id_first_name">First Name</label>
                    </div>
                    <div class="input-field col s12 m6">
                       {{ form.last_name }}
                        <label for="id_last_name">Last Name</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s12 m6">
                       {{ form.id_number }}
                        <label for="id_id_number">ID NUMBER</label>
                    </div>
                    <div class="input-field col s12 m6">
                         {{ form.email_address }}
                        <label for="id_email_address">EMAIL ADDRESS</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s12 m12">
                        {{ form.phone_number }}
                        <label for="id_phone_number">Phone Number</label>
                    </div>
                </div>
                 <div class="row">
                    <div class="input-field col s12 m6">
                          {{ form.sacco_reg_no }}
                        <label for="id_sacco_reg_no">Sacco Registration Number</label>
                    </div>
                    <div class="input-field col s12 m6">
                       {{ form.sacco_name }}
                        <label for="id_sacco_name">SACCO NAME</label>
                    </div>
                </div>
                <!--
                <div class="row">
                    <div class="file-field input-field">
                      <div class="btn">
                        <span>License Certificate</span>
                        <input type="file">
                      </div>
                      <div class="file-path-wrapper">
                        <input class="file-path validate" type="text">
                      </div>
                    </div>
                </div>-->
                <div class="row">
                    <div class="input-field col 12 m6 offset-m2">
                        <button class="btn btn-block mat360-btn" type="submit">Send Us Request</button>
                    </div>
                </div>

           </div>

        </form>
    </div>


     <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    </body>
  </html>