home/urls.py
from django.urls import path

from home import views
from traveller import  views as tview
app_name='home'
urlpatterns=[
    path('',views.Index.as_view(),name='index'),
    path('saccos/',views.Saccos.as_view(),name='saccos'),
    path('book_ride/',views.book_ride,name='book-ride'),
    path('signin/',tview.log_user_in,name='signin'),
    path('signup/',tview.create_customer_account,name='signup'),
    path('logout/',views.logout_view,name='logout'),


   #validation ajax requests
    path('ajax/list_sacco/',views.check_saccos,name='check-saccos'),
    path('ajax/list_rides/', views.get_sacco_rides, name='listrides'),
    #path('ajax/get_ride_details/', views.get_ride_details, name='getridedetails'),
    path('ajax/get-active-fare/', views.getActivePrice, name='getactivefare'),
    path('ajax/ride_details/',views.get_ride_important_details,name='rideimportantdetails'),
    path('confirmation/',views.confirmation_url,name='confirmation'),
    path('validation/',views.validation_url,name='validation'),
    path('try-payments/',views.process_payment,name='mobile_payment'),

]

mat360/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    #path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('admin/',include('mat360admin.urls')),

    path('saccoManager/',include('sacco_manager.urls')),
    path('stageController/', include('stagecontroller.urls')),
    path('traveller/',include('traveller.urls')),
    path('driver/',include('driver.urls')),

    #api urls
    path('traveller/api/v1/',include('traveller.api.urls')),
]

sacco_manager/urls.py
from django.urls import path
from sacco_manager import views

app_name='sacco_manager'

urlpatterns=[
    path('request_sacco_registration/',views.save_sacco_registration_requests,name='request-sacco-registration'),
    path('accounts/',views.sacco_manager_dashboard,name='sacco-manager-dashboard'),
    path('accounts/new_vehicle',views.new_vehicle_registration,name='new-vehicle-registration'),
    path('accounts/our_fleet',views.get_fleet,name='our-fleet'),
    path('accounts/new_stage_controller', views.register_stage_controller, name='new-controller'),
    path('accounts/our_settings', views.sacco_settings, name="sacco-settings"),
    path('accounts/vehicle_statistics',views.vehicle_statistics,name='vehicle_stats'),
    #path('accounts/route-management/',views.route_management_home,name='route_management'),
    #Company Finances
    path('accounts/sacco_finances/',views.SaccoFinancesPage.as_view(),name='sacco-finances'),
    path('accounts/sacco_finances/current_balance_distribution',views.CurrentBalanceDistribution.as_view(),name='sacco-current-balance'),
    path('accounts/route-management/register_route', views.register_vehicle_route, name='register_route'),
    #Ajax Based Functons
    path('accounts/ajax/VehicleStats/',views.getVehicleStatistics,name='ajax-vehicle-stats'),
    path('',views.logout_view,name='logout'),
]

stagecontroller/urls.py
from django.urls import path

from stagecontroller import views
app_name='stagecontroller'

urlpatterns=[
    path('accounts/update_fare/',views.update_fare,name='update-fare'),
    path('accounts/available_rides/',views.avail_driver_activated_rides,name='confirm-driver-rides'),
    path('accounts/active_rides/',views.get_active_rides,name='activerides'),
]

stagecontroller/models.py
from django.db import models
# Create your models here.
from django.utils.timezone import now

from sacco_manager.models import StageController, Sacco, Route


class FareUpdate(models.Model):
    sacco=models.ForeignKey(Sacco,on_delete=models.CASCADE)
    route=models.ForeignKey(Route,on_delete=models.CASCADE)
    amount=models.DecimalField(decimal_places=2,max_digits=10,blank=False,null=False)
    stagecontroller=models.ForeignKey(StageController,on_delete=models.CASCADE)
    created=models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table='ride_fare'

stagecontroller/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.http import JsonResponse
from django.shortcuts import render
from django.utils.timezone import now
from django.views.generic import TemplateView
from sacco_manager.models import Vehicle, VControl, Route, Sacco, StageController
from sacco_manager.algorithms.algo import FilterClass
from stagecontroller.models import FareUpdate



#This is the function to confirm available rides
@login_required(login_url='admin:admin-login')
def avail_driver_activated_rides(request):
    try:
        all_rides=VControl.objects.filter(v_availability_by_driver=True).filter(controller_confirmation_status=False).filter(station=request.user.stagecontroller.station)
    except VControl.DoesNotExist:
        all_rides=None

    if request.method == 'POST':
        VControl.objects.filter(pk=request.POST['v_id']).update(controller_confirmation_status=True,time_of_confirmation_by_controller=now())
        messages.success(request,'Vehicle activated successfully')
    return render(request,'stage_controller/activate_driver_requests.html',{'rides':all_rides})
@login_required(login_url='admin:admin-login')
def update_fare(request):
    dapartureT= request.user.stagecontroller.station

    #Get all the updated rides
    stagecontrollerI = StageController.objects.get(pk=request.user.stagecontroller.id_number)
    activeFareI=FareUpdate.objects.filter(stagecontroller=stagecontrollerI)


    #destinations=Route.objects.filter(Q(departure= dapartureT.upper())| Q(destination= dapartureT.upper()) ).values_list('departure',flat=True).distinct()
    if request.method == 'POST':
        departuretown=request.POST['from']
        destinationT=request.POST['destination']
        amount=request.POST['amount']

        d_departure = ''
        d_destination = ''
        filterI = FilterClass()
        if filterI.prepare_town_search(departuretown, destinationT):
            d_departure = departuretown.upper()
            d_destination = destinationT.upper()
        else:
            d_departure = destinationT.upper()
            d_destination = departuretown.upper()
        try:
            sacco=Sacco.objects.get(pk=request.user.stagecontroller.sacco.sacco_reg_no)
            route=Route.objects.get(Q(departure=d_departure),Q(destination=d_destination),Q(sacco=request.user.stagecontroller.sacco.sacco_reg_no))

            fareupdate = FareUpdate()
            fareupdate.sacco = sacco
            fareupdate.route = route
            fareupdate.stagecontroller=stagecontrollerI
            fareupdate.amount = amount
            fareupdate.save()
            messages.success(request, 'Your Fare has been updated successfuly')
        except Route.DoesNotExist:
            messages.error(request,"The route is not registered by the sacco")


    return render(request,'stage_controller/update_fare.html',{'fare':activeFareI})
@login_required(login_url='admin:admin-login')
def get_active_rides(request):
    stagecontrollerI = StageController.objects.get(pk=request.user.stagecontroller.id_number)
    sacco = Sacco.objects.get(pk=request.user.stagecontroller.sacco.sacco_reg_no)
    active_rides=Vehicle.objects.filter(vcontrol__station=stagecontrollerI.station).filter(vcontrol__controller_confirmation_status=True).filter(sacco=sacco)
   # total_rides=Vehicle.objects.filter(vcontrol__station=stagecontrollerI.station).filter(vcontrol__controller_confirmation_status=True).filter(sacco=sacco).count()

    return render(request, 'stage_controller/activated_rides.html', {'activerides': active_rides,'totalrides':range(active_rides.count())})

templates/stage_controller/activate_driver_requests.html
{% extends 'stage_controller/base.html' %}
{% load static %}
{% block content %}
<div id="main">
 <div class="container">
     <div class="row">
         <div class="col s12 m12">
             <p class="center-align"><b><u>STAGE CONTROLLER DASHBOARD</u></b></p>
             {% if messages  %}
                 {% for message in messages %}
                     <p class="center-align green-text">{{ message }}</p>
                 {% endfor %}
             {% endif %}
         </div>
     </div>

     <div class="row">
         <div class="col s12">
             <div class="card">
                 <div class="card-content">
                     <table class="highlight responsive-table">
        <thead>
          <tr>
              <th>V.Number</th>
              <th>Driver Name</th>
              <th>Confirmed BY</th>
               <th>Confirmed At</th>
               <th>My Action</th>
          </tr>
        </thead>

        <tbody>
         {% if rides  %}
            {% for ride in rides  %}
                 <tr>
            <td>{{ ride.vehicle.v_number }}</td>
            <td>{{ ride.vehicle.driver.user.first_name }} {{ ride.vehicle.driver.user.last_name }} </td>
            <td>{{ ride.vehicle.driver.user.first_name }} {{ ride.vehicle.driver.user.last_name }}</td>
               <td>{{ ride.time_available_by_driver|time }}</td>
               <td><form method="post" action="">
                   {% csrf_token %}
                   <input type="hidden" value="{{ ride.id }}" name="v_id">
                   <button class="btn custom-btn">Confirm Availability</button>
               </form> </td>
          </tr>

            {% endfor %}
            {% else %}
            <p class="center-align red-text">There are no available rides</p>

        {% endif %}
        </tbody>
      </table>
                 </div>
             </div>
         </div>
     </div>


  <!--This is the column for tables-->
 </div>
</div>






{% endblock %}

templates/stage_controller/activated_rides.html
{% extends 'stage_controller/base.html' %}
{% load static %}
{% block content %}
<div id="main">
 <div class="container">
     <div class="row">
         <div class="col s12 m12">
             <p class="center-align"><b><u>STAGE CONTROLLER DASHBOARD</u></b></p>
         </div>
     </div>

     <div class="row">
         <div class="col s12">
             <div class="card">
                 <div class="card-content">
                 <p class="center-align purple-text">ALL ACTIVE RIDES <span class="badge purple">{{ activerides|length }}</span> </p>

                     <table class="highlight responsive-table">
        <thead>
          <tr>
               <th>#</th>
              <th>V.Number</th>
               <th>Departure Town</th>
              <th>Destination Town</th>
              <th>Driver Name</th>
              <th>Capacity</th>
              <th>ACTIVE BOOKINGS</th>

          </tr>
        </thead>

        <tbody>
         {% if activerides  %}

            {% for ride in activerides  %}
                 <tr>
                 <td>{{ forloop.counter }}</td>
            <td>{{ ride.v_number }}</td>
                      <td>{{ ride.route.destination }}</td>
                     <td>{{ ride.route.departure }}</td>
            <td>{{ ride.driver.user.first_name }} {{ ride.driver.user.last_name }} </td>
            <td>{{ ride.capacity}} </td>
                 <td>{{ ride.activeBookings }}</td>

          </tr>

            {% endfor %}

            {% else %}
            <p class="center-align red-text">There are no available rides</p>

        {% endif %}
        </tbody>
      </table>
                 </div>
             </div>
         </div>
     </div>


  <!--This is the column for tables-->
 </div>
</div>






{% endblock %}

templates/stage_controller/base.html
<!DOCTYPE html>
<html class="loading" lang="en" data-textdirection="ltr">
  <!-- BEGIN: Head-->
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
    <meta name="description" content="Materialize is a Material Design Admin Template,It's modern, responsive and based on Material Design by Google.">
    <meta name="keywords" content="materialize, admin template, dashboard template, flat admin template, responsive admin template, eCommerce dashboard, analytic dashboard">
    <meta name="author" content="ThemeSelect">

      {% load static %}
    <title>Mat360|The leading public ridesharing application in Kenya</title>
    <script  src="https://code.jquery.com/jquery-3.5.1.min.js"  integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="  crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- BEGIN: VENDOR CSS-->
    <link rel="stylesheet" type="text/css" href="{% static 'controlled/css/vendors.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'controlled/css/animate.css' %}">
    <!-- END: VENDOR CSS-->
    <!-- BEGIN: Page Level CSS-->
    <link rel="stylesheet" type="text/css" href="{% static 'controlled/css/materialize.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'controlled/css/style.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'controlled/css/dashboard-modern.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'controlled/css/intro.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/main.css' %}">
       <link rel="stylesheet" href="{% static 'assets/css/new-main.css' %}">

     <link rel="shortcut icon" href="{% static 'assets/media/logo.ico' %}" type="image/x-icon"/>



  </head>
  <!-- END: Head-->
  <body class="vertical-layout vertical-menu-collapsible page-header-dark vertical-modern-menu preload-transitions 2-columns   " data-open="click" data-menu="vertical-modern-menu" data-col="2-columns">

    <!-- BEGIN: Header-->
    <header class="page-topbar" id="header">
      <div class="navbar navbar-fixed">
        <nav class="navbar-main navbar-color nav-collapsible sideNav-lock navbar-dark gradient-45deg-indigo-purple no-shadow">
          <div class="nav-wrapper">
            <ul class="navbar-list right">
              <li><a class="waves-effect waves-block waves-light profile-button" href="javascript:void(0);" data-target="profile-dropdown">{{ user.get_username }}<span>

              </span><span class="material-icons">keyboard_arrow_down</span> </a></li>

            </ul>


            <ul class="dropdown-content" id="profile-dropdown">
                <li><a class="grey-text text-darken-1" href=""><i class="material-icons">person_outline</i> Profile</a></li>
                <li class="divider"></li>
                <li><a class="grey-text text-darken-1" href="{% url 'sacco_manager:logout' %}"><i class="material-icons">keyboard_tab</i> Logout</a></li>
            </ul>
          </div>
        </nav>
      </div>
    </header>
    <!-- END: Header-->

    <aside class="sidenav-main nav-expanded nav-lock nav-collapsible sidenav-light sidenav-active-square">
      <div class="brand-sidebar">
               <p class="center-align">Mat360 Stage Controller</p>
      </div>
      <ul class="sidenav sidenav-collapsible leftside-navigation collapsible sidenav-fixed menu-shadow" id="slide-out" data-menu="menu-navigation" data-collapsible="menu-accordion">
        <li class="active bold"><a class="collapsible-header waves-effect waves-cyan" href="{% url 'stagecontroller:confirm-driver-rides' %}" ><i class="material-icons">home</i><span class="menu-title" data-i18n="Dashboard">DashBoard</span></a>
         </li>
          <li class="navigation-header"><a class="navigation-header-text">Sacco Managers</a><i class="navigation-header-icon material-icons">more_horiz</i>
        </li>
         <li class="bold"><a class="waves-effect waves-cyan " href="{% url 'stagecontroller:update-fare' %}"><i class="material-icons">person_outline</i><span class="menu-title" data-i18n="User Profile">Update Fare Prices</span></a></li>
         <li class="bold"><a class="waves-effect waves-cyan " href="{% url 'stagecontroller:confirm-driver-rides' %}"><i class="material-icons">list</i><span class="menu-title" data-i18n="User Profile">Confirm Activated Rides</span></a></li>
         <li class="bold"><a class="waves-effect waves-cyan " href="{% url 'stagecontroller:activerides' %}"><i class="material-icons">list</i><span class="menu-title" data-i18n="User Profile">Active Rides</span></a></li>


      </ul>
      <div class="navigation-background"></div><a class="sidenav-trigger btn-sidenav-toggle btn-floating btn-medium waves-effect waves-light hide-on-large-only" href="#" data-target="slide-out"><i class="material-icons">menu</i></a>
    </aside>
    <!-- END: SideNav-->








    <!-- BEGIN: Page Main-->

    {% block content %}

    {% endblock %}
    <!-- END: Page Main-->









    <!-- BEGIN: Footer-->

    <footer class="page-footer footer footer-static footer-dark gradient-45deg-indigo-purple gradient-shadow navbar-border navbar-shadow">
      <div class="footer-copyright">
        <div class="container"><span>&copy; 2020 <a href="" target="_blank">Mat360</a> All rights reserved.</span><span class="right hide-on-small-only">Design and Developed by <a href="hornafrictech.com">HornAfricTech</a></span></div>
      </div>
    </footer>

       <!-- BEGIN VENDOR JS-->
    <script src="{% static 'controlled/js/vendors.min.js' %}"></script>
    <!-- BEGIN VENDOR JS-->
    <!-- BEGIN PAGE VENDOR JS-->
    <script src="{% static 'controlled/jss/chart.min.js' %}"></script>
    <!-- BEGIN THEME  JS-->
    <script src="{% static 'controlled/js/plugins.min.js' %}"></script>
    <script src="{% static 'controlled/js/search.min.js' %}"></script>
    <script src="{% static 'controlled/js/customizer.min.js' %}"></script>
    <!-- END THEME  JS-->
    <!-- BEGIN PAGE LEVEL JS-->
    <script src="{% static 'controlled/js/dashboard-modern.js' %}"></script>
    <script src="{% static 'controlled/js/intro.min.js' %}"></script>
    <!-- END PAGE LEVEL JS-->

  </body>
</html>

templates/stage_controller/update_fare.html
{% extends 'stage_controller/base.html' %}
{% load static %}
{% block content %}
<div id="main">
 <div class="container">
     <div class="row">
         <div class="col s12 m12">
             <h5 class="center-align">STAGE CONTROLLER FARE UPDATE</h5>
         </div>
     </div>
     <div class="row">
         <div class="col s12 m4">
             <div class="card">
                 <div class="card-content purple-text">
                     <span class="card-title center-align">FARE UPDATE FORM</span>
                     <form method="post" action="{% url 'stagecontroller:update-fare' %}">
                         {% csrf_token %}
                         {% if messages %}
                         {% for message in messages %}
                            <p class="center-align green-text">{{ message }}</p>
                         {% endfor %}
                     {% endif %}
                    <div class="row">
                        <div class="input-field col s12 m12">
                            <input id="from" name="from" type="text" value="{{ request.user.stagecontroller.station }}" class="validate" readonly>
                            <label for="from">From</label>
                        </div>
                    </div>
                      <div class="row">

                        <div class="input-field col s12 m12">
                            <input id="destination" name="destination" type="text"  class="validate" >
                            <label for="destination">From</label>
                        </div>

                    </div>
                     <div class="row">
                        <div class="input-field col s12 m12">
                            <input type="number" id="amount" name="amount" class="validate" >
                            <label for="amount">Amount</label>
                        </div>
                    </div>
                     <div class="row">
                        <div class="input-field col s12 m12">
                            <button type="submit" class="btn btn-block mat360-btn">Update Fare</button>
                        </div>
                    </div>
                           </form>
                 </div>
             </div>
         </div>
        <!--SECOND COLUMN-->
        <div class="col s12 m7 offset-m1">
            <p>These shows all the active fares available</p>
            <div class="card">
                <div class="card-content">
                    <table>
        <thead>
          <tr>
              <th>Route CODE</th>
              <th>Departure</th>
              <th>Destination</th>
               <th>Fare Amount</th>
               <th>Date Updated</th>
          </tr>
        </thead>

        <tbody>
        {% if fare %}
           {% for fareI in fare %}
               <tr>
                <td>{{ fareI.route.id }}</td>
                <td>{{ fareI.route.departure }}</td>
                <td>{{ fareI.route.destination }}</td>
               <td>{{ fareI.amount }}</td>
               <td>{{ fareI.created}}</td>

              </tr>
            {% endfor %}
            {% else %}
            <p class="center-align red-text">No activated Fares now in the database</p>
        {% endif %}

        </tbody>
      </table>
                </div>
            </div>
        </div>
     </div>




 </div>
</div>


{% endblock %}