home/urls.py
from django.urls import path

from home import views
from traveller import  views as tview
app_name='home'
urlpatterns=[
    path('',views.Index.as_view(),name='index'),
    path('saccos/',views.Saccos.as_view(),name='saccos'),
    path('book_ride/',views.book_ride,name='book-ride'),
    path('signin/',tview.log_user_in,name='signin'),
    path('signup/',tview.create_customer_account,name='signup'),
    path('logout/',views.logout_view,name='logout'),


   #validation ajax requests
    path('ajax/list_sacco/',views.check_saccos,name='check-saccos'),
    path('ajax/list_rides/', views.get_sacco_rides, name='listrides'),
    #path('ajax/get_ride_details/', views.get_ride_details, name='getridedetails'),
    path('ajax/get-active-fare/', views.getActivePrice, name='getactivefare'),
    path('ajax/ride_details/',views.get_ride_important_details,name='rideimportantdetails'),
    path('confirmation/',views.confirmation_url,name='confirmation'),
    path('validation/',views.validation_url,name='validation'),
    path('try-payments/',views.process_payment,name='mobile_payment'),

]

mat360/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    #path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('admin/',include('mat360admin.urls')),

    path('saccoManager/',include('sacco_manager.urls')),
    path('stageController/', include('stagecontroller.urls')),
    path('traveller/',include('traveller.urls')),
    path('driver/',include('driver.urls')),

    #api urls
    path('traveller/api/v1/',include('traveller.api.urls')),
]

sacco_manager/urls.py
from django.urls import path
from sacco_manager import views

app_name='sacco_manager'

urlpatterns=[
    path('request_sacco_registration/',views.save_sacco_registration_requests,name='request-sacco-registration'),
    path('accounts/',views.sacco_manager_dashboard,name='sacco-manager-dashboard'),
    path('accounts/new_vehicle',views.new_vehicle_registration,name='new-vehicle-registration'),
    path('accounts/our_fleet',views.get_fleet,name='our-fleet'),
    path('accounts/new_stage_controller', views.register_stage_controller, name='new-controller'),
    path('accounts/our_settings', views.sacco_settings, name="sacco-settings"),
    path('accounts/vehicle_statistics',views.vehicle_statistics,name='vehicle_stats'),
    #path('accounts/route-management/',views.route_management_home,name='route_management'),
    #Company Finances
    path('accounts/sacco_finances/',views.SaccoFinancesPage.as_view(),name='sacco-finances'),
    path('accounts/sacco_finances/current_balance_distribution',views.CurrentBalanceDistribution.as_view(),name='sacco-current-balance'),
    path('accounts/route-management/register_route', views.register_vehicle_route, name='register_route'),
    #Ajax Based Functons
    path('accounts/ajax/VehicleStats/',views.getVehicleStatistics,name='ajax-vehicle-stats'),
    path('',views.logout_view,name='logout'),
]

sacco_manager/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.utils.timezone import now

from mat360admin.models import Mat360SystemUsers


class SaccoRegistrationRequests(models.Model):
    first_name=models.CharField(max_length=20,blank=False,null=False)
    last_name = models.CharField(max_length=20, blank=False, null=False)
    id_number = models.CharField(max_length=20, blank=False, null=False,primary_key=True)
    email_address = models.CharField(max_length=100, blank=False, null=False,unique=True)
    phone_number = models.CharField(max_length=20, blank=False, null=False,unique=True)
    sacco_reg_no = models.CharField(max_length=50, blank=False, null=False)
    sacco_name = models.CharField(max_length=100, blank=False, null=False)
    date_reguested=models.DateTimeField(auto_now_add=now())
    application_status=models.CharField(max_length=15,default='in_progress',blank=False)

    class Meta:
        db_table='sacco_requests'


class SaccoManager(models.Model):
    user = models.OneToOneField(Mat360SystemUsers, on_delete=models.CASCADE,related_name='sacco_manager')
    id_number = models.CharField(max_length=8,primary_key=True)
    date_registered = models.DateTimeField(auto_now=now())

    class Meta:
        db_table='sacco_manager'
class Sacco(models.Model):
    sacco_manager = models.OneToOneField(SaccoManager, on_delete=models.CASCADE,related_name='sacco')
    sacco_reg_no = models.CharField(max_length=50,primary_key=True)
    sacco_name=models.CharField(max_length=100,blank=False,null=False)
    date_registered = models.DateTimeField(auto_now=now())

    class Meta:
        db_table='sacco'




class Route(models.Model):
    departure=models.CharField(max_length=30,blank=False,null=False)
    destination=models.CharField(max_length=30,blank=False,null=False)
    sacco=models.ForeignKey(Sacco,on_delete=models.CASCADE)

    class Meta:
        db_table='routes'

class Driver(models.Model):
    user = models.OneToOneField(Mat360SystemUsers, on_delete=models.CASCADE, related_name='driver')
    id_number = models.CharField(max_length=8, primary_key=True)
    date_registered = models.DateTimeField(auto_now=now())

    class Meta:
        db_table='sacco_driver'

class Vehicle(models.Model):
    sacco=models.ForeignKey(Sacco,on_delete=models.CASCADE,related_name='sacco')
    v_number=models.CharField(max_length=7,primary_key=True)
    capacity=models.IntegerField()
    route=models.ForeignKey(Route,on_delete=models.CASCADE,related_name='route')
    driver=models.OneToOneField(Driver,on_delete=models.CASCADE,related_name='driver')
    date_registered=models.DateTimeField(auto_now=now())

    def activeBookings(self):
        active_bookings=VehicleBookings.objects.filter(vehicle=self.v_number).filter(booking_status='active').count()
        return active_bookings



    class Meta:
        db_table='vehicle'




class StageController(models.Model):
    user=models.OneToOneField(Mat360SystemUsers,on_delete=models.CASCADE,related_name='stagecontroller')
    id_number=models.CharField(max_length=8,primary_key=True)
    station=models.CharField(max_length=50,null=False,blank=False)
    sacco=models.ForeignKey(Sacco,on_delete=models.CASCADE,related_name='sacco_stagecontroller')
    phone_number=models.CharField(max_length=10,unique=True,blank=False)

    class Meta:
        db_table='stage_controller'
class VControl(models.Model):
    vehicle=models.ForeignKey(Vehicle,on_delete=models.CASCADE,related_name='vcontrol')
    station=models.CharField(max_length=50,blank=False,null=False)
    v_availability_by_driver=models.BooleanField(default=False)
    controller_confirmation_status=models.BooleanField(default=False)
    time_available_by_driver=models.DateTimeField(default=now())
    time_of_confirmation_by_controller=models.DateTimeField(null=True,blank=True)

    class Meta:
        db_table='vehiclecontrol'


class VehicleBookings(models.Model):
    vehicle=models.ForeignKey(Vehicle,on_delete=models.CASCADE)
    traveller=models.ForeignKey(Mat360SystemUsers,on_delete=models.CASCADE)
    booking_status=models.CharField(max_length=20,default='active')
    created=models.DateTimeField(auto_now_add=now())
    booking_code=models.PositiveIntegerField(null=False,blank=False)
    payment_status=models.BooleanField(default=False)

    class Meta:
        db_table='vbookings'
#This is the model that will be updated if the vehicle is full;
class VehicleStatus(models.Model):
    vehicle=models.ForeignKey(Vehicle,on_delete=models.CASCADE)
    status=models.CharField(max_length=10)
    class Meta:
        db_table='vstatus'
#This is a model to store all transactions
class FareTransactions(models.Model):
    vehicle=models.ForeignKey(Vehicle,on_delete=models.CASCADE)
    traveller=models.ForeignKey(Mat360SystemUsers,on_delete=models.CASCADE)
    amount=models.DecimalField(max_digits=10,decimal_places=2)
    date_transacted=models.DateTimeField(auto_now_add=now())
    departure_town=models.CharField(max_length=50,blank=False,default='XYZ')
    destination_town=models.CharField(max_length=50,blank=False,default="ZYX")
    class Meta:
        db_table='fareTransactions'
#model that will be used for Sacco Deductions;
class VehicleTrips(models.Model):
    vehicle=models.ForeignKey(Vehicle,on_delete=models.CASCADE)
    initial_booking=models.DateTimeField(auto_now_add=now())
    final_booking=models.DateTimeField(blank=True)

sacco_manager/forms.py
from django import forms
from mat360admin.models import Mat360SystemUsers
from sacco_manager.models import SaccoRegistrationRequests, Vehicle


class SaccoRequestRegistrationForm(forms.ModelForm):
    class Meta:
        model = SaccoRegistrationRequests
        fields = ('first_name','last_name','id_number','email_address','phone_number','sacco_reg_no','sacco_name')
class VehicleRegistrationForm(forms.ModelForm):
    #Driver_details
    first_name = forms.CharField(max_length=40, required=True, widget=forms.TextInput())
    last_name = forms.CharField(max_length=40, required=True, widget=forms.TextInput())

    id_number = forms.CharField(max_length=8, required=True, widget=forms.TextInput())

    phone_number = forms.CharField(max_length=100, required=True, widget=forms.TextInput())
    email_address = forms.CharField(max_length=100, required=True, widget=forms.TextInput())

    class Meta:
        model=Vehicle
        fields = ('v_number', 'capacity','first_name','last_name','id_number','phone_number','email_address')
class StageControllerRegistrationForm(forms.ModelForm):
    id_number=forms.CharField(max_length=8,required=True,widget=forms.TextInput())
    station = forms.CharField(max_length=40, required=True, widget=forms.TextInput())
    phone_number = forms.CharField(max_length=10, required=True, widget=forms.TextInput())


    class Meta:
        model=Mat360SystemUsers
        fields = ('first_name', 'last_name','email','id_number','phone_number','station')

templates/sacco_manager/account_activation.html
{% autoescape off %}
Hi {{ user.username }},
You have been registered as a stage controller of {{ sacco_name }}.To activate your account ,kindly click the confirmation link below.
http://{{ domain }}
{% endautoescape %}

templates/sacco_manager/current_balance_distribution.html
{% extends 'sacco_manager/sacco_manager_base.html' %}
{% load static %}
{% block content %}
<div id="main">
  <div class="row">
      <div class="col  s12 center-align"><h4 class="purple-text"><u>Current Finance Balance</u></h4></div>
  </div>
 <!--This is the Second Row-->
<div class="row">
    <div class="col s12 m4">
        <div class="card">
            <div class="card-content center-align">
                <h4>{{ finance_summary.total_amount }}</h4>
                <p>Grand Amount Collected</p>
            </div>
        </div>
    </div>
    <!--This is the Second Column-->
     <div class="col s12 m4">
        <div class="card">
            <div class="card-content center-align">
                <h4>{{ finance_summary.sacco_finances}}</h4>
                <p>Sacco Collections</p>
            </div>
        </div>
    </div>
    <!--This is the Third and Final Column-->
     <div class="col s12 m4">
        <div class="card purple white-text">
            <div class="card-content center-align">
                <h4 class="white-text">{{ finance_summary.owner_finances }}</h4>
                <p>Owner Amount</p>
            </div>
        </div>
    </div>
    <!--End of Columns-->
</div>
<!--The Third Row-->
<div class="row">
    <div class="col s12">
            <table>
        <thead>
          <tr>
              <th>#</th>
              <th>Vehicle Number</th>
              <th>Number of Trips</th>
              <th>Total Amount</th>
              <th>Sacco Deductions</th>
              <th>Net Amount</th>
          </tr>
        </thead>

        <tbody>
        {% for ride in vehicle_individual_contributions  %}
          <tr>
            <td>{{forloop.counter}}</td>
            <td>{{ ride.bill_refnumber.v_number }}</td>
            <td>{{ ride.bill_refnumber.capacity }}</td>
            <td>{{ ride.bill_refnumber.capacity }}</td>
            <td>{{ ride.transaction_amount }}</td>
            <td>{{ ride.transaction_amount }}</td>
          </tr>
        {% endfor %}

        </tbody>
      </table>
    </div>
</div>
<!--This is the Fourth Row-->
<div class="row">
    <div class="col s12 m6 right">
        <button class="btn btn-block mat360-btn">Process Bulk Owner Payments</button>
    </div>
</div>
</div>
{% endblock %}

templates/sacco_manager/new_stage_controller.html
{% extends 'sacco_manager/sacco_manager_base.html' %}
{% load static %}
{% block content %}
<div id="main">
    <div class="row">
        <div class="col s12 m12 l12">
            <div class="container">
              <div class="row">
              <div class="col s12 m7">
                  <div class="card">
                      <div class="card-content">
                          <p class="center-align purple-text">ALL REGISTERED STAGE CONTROLLER</p>
                           <table class="highlight responsive-table">
                                <thead>
                                  <tr>
                                       <th>#</th>
                                      <th>FIRST NAME</th>
                                       <th>LAST NAME</th>
                                       <th>PHONE</th>
                                      <th>STATION</th>

                                  </tr>
                                </thead>

                                <tbody>
                                {% if controllers %}
                                    {% for controller in controllers %}
                                        <tr>
                                           <td>{{ forloop.counter }}</td>
                                           <td>{{ controller.user.first_name }}</td>
                                           <td>{{ controller.user.last_name }}</td>
                                           <td>{{ controller.phone_number }}</td>
                                           <td>{{ controller.station }}</td>

                                        </tr>
                                    {% endfor %}
                                    {% else %}
                                    <p class="center-align red-text">There are no registered stage controllers in our database</p>
                                {% endif %}
                                </tbody>
                           </table>
                      </div>
                  </div>
              </div>
               <div class="col s12 m5">
       <div class="card">
                <div class="card-content" >
                    <span class="center-align">  <span class="card-title">NEW STAGE CONTROLLER REGISTRATION FORM</span>
                                <div class="divider"></div></span>
                 <div class="row">
                         <div class="col s12">
                             <p class="center-align pink-text"><u>Stage Controller Details</u> -Fill Controller details here</p>
                         </div>
                     </div>
                <div class="row">
                    <div class="col s12 m12 l12">
                        <div class="form">
                     <form class="col s12" method="post" action="">
                         {% csrf_token %}
                         {% if messages %}
                             {% for message in messages %}
                                 <p class="center-align green-text">{{ message }}</p>
                             {% endfor %}
                         {% endif %}
      <div class="row">
          <div class="input-field col s12 m6">
         {{ form.first_name }}
          <label for="id_first_name">First Name</label>
        </div>
           <div class="input-field col s12 m6">
          {{ form.last_name }}
          <label for="id_last_name">Last Name</label>
        </div>
      </div>

      <div class="row">
        <div class="input-field col s12 m6">
            {{ form.id_number }}
          <label for="id_id_number">ID Number</label>
        </div>
          <div class="input-field col s12 m6">
              {{ form.phone_number }}
             <label for="id_phone_number">Phone Number</label>
          </div>
      </div>

                      <div class="row">
                         <div class="input-field col s12">
                              {{ form.email }}
                             <label for="id_email_address">Email Address</label>
                         </div>

                     </div>

                     <div class="row">
                         <div class="input-field col s12">
                              {{ form.station }}
                             <label for="id_station">Station</label>
                         </div>

                     </div>










     <div class="row">
         <div class="input-field col s12 m6 offset-m3">
             <button type="submit" class="btn btn-block mat360-btn">Register Controller</button>
         </div>
     </div>


    </form>
                    </div>
                    </div>
                </div>

                </div>
            </div>
    </div>

           </div>
           </div>
    </div>
</div>
</div>
{% endblock %}

templates/sacco_manager/new_vehicle.html
{% extends 'sacco_manager/sacco_manager_base.html' %}
{% load static %}
{% block content %}
<div id="main">
    <div class="row">
        <div class="col s12 m12 l12">
            <div class="container">
              <div class="row">
               <div class="col s12 m6 offset-m2">
       <div class="card">
       {% if all_routes %}
                <div class="card-content" >
                    <span class="center-align">  <span class="card-title">NEW VEHICLE REGISTRATION FORM</span>
                                <div class="divider"></div></span>
                <div class="row">
                    <div class="col s12 m12 l12">
                        <div class="form">
                     <form class="col s12" method="post" action="">
                         {% csrf_token %}
                         {% if messages %}
                             {% for message in messages %}
                                 <p class="center-align">{{ message }}</p>
                             {% endfor %}
                         {% endif %}
      <div class="row">
          <div class="input-field col s12">
         {{ form.v_number }}
          <label for="id_v_number">Vehicle Plate Number</label>
        </div>

      </div>
      <div class="row">
        <div class="input-field col s12">
          {{ form.capacity }}
          <label for="id_capacity">Vehicle Capacity</label>
        </div>
      </div>
      <div class="row">
           <div class="input-field col s12">

    <select name="vehicle_route">
      <option value="" disabled selected>CHOOSE ROUTE</option>
        {% for route in all_routes %}
             <option value="{{ route.id }}">{{ route.departure }}-{{ route.destination }}</option>
        {% endfor %}

    </select>
    <label>Select Vehicle Route</label>
  </div>

      </div>
                     <div class="row">
                         <div class="col s12">
                             <p class="center-align pink-text"><u>Driver Details</u> -Fill driver details here</p>
                         </div>
                     </div>


                     <div class="row">
                         <div class="input-field col s12 m6">
                              {{ form.first_name }}
                             <label for="id_first_name">First Name</label>
                         </div>
                         <div class="input-field col s12 m6">
                              {{ form.last_name }}
                             <label for="id_last_name">Last Name</label>
                         </div>
                     </div>
                     <div class="row">
                         <div class="input-field col s12 m6">
                              {{ form.id_number }}
                             <label for="id_id_number">ID NUMBER</label>
                         </div>
                         <div class="input-field col s12 m6">
                              {{ form.phone_number }}
                             <label for="id_phone_number">PHONE NUMBER</label>
                         </div>
                     </div>
                     <div class="row">
                         <div class="input-field col s12">
                              {{ form.email_address }}
                             <label for="id_email_address">Email Address</label>
                         </div>

                     </div>




     <div class="row">
         <div class="input-field col s12 m6 offset-m3">
             <button type="submit" class="btn btn-block mat360-btn">Register Vehicle</button>
         </div>
     </div>


    </form>
                    </div>
                    </div>
                </div>

                </div>
           {% else %}
           <p class="center-align red-text">You have not registered any routes.Click <a href="">Here</a> to register routes first </p>
       {% endif %}
            </div>
    </div>

           </div>
           </div>
    </div>
</div>
</div>
{% endblock %}

templates/sacco_manager/sacco_finances.html
{% extends 'sacco_manager/sacco_manager_base.html' %}
{% load static %}
{% block content %}
<div id="main">
  <div class="row">
      <div class="col  s12 center-align"><h4 class="purple-text"><u>Company Finances OverView</u></h4></div>
  </div>
 <!--This is the Second Row-->
<div class="row">
    <div class="col s12 m4">
        <div class="card">
            <div class="card-content center-align">
                <h4>{{ finance_summary.total_amount }}</h4>
                <p>Total Amount Collected</p>
            </div>
        </div>
    </div>
    <!--This is the Second Column-->
     <div class="col s12 m4">
        <div class="card">
            <div class="card-content center-align">
                <h4>{{ finance_summary.sacco_finances }}</h4>
                <p>Sacco Collections</p>
            </div>
        </div>
    </div>
    <!--This is the Third and Final Column-->
     <div class="col s12 m4">
        <div class="card purple white-text">
            <a href="{% url 'sacco_manager:sacco-current-balance' %}">
            <div class="card-content center-align">
                <h4 class="white-text">{{ finance_summary.owner_finances }}</h4>
                <p>Available Balance</p>
            </div>
                </a>
        </div>
    </div>
    <!--End of Columns-->
</div>
<!--The Third Row-->
<div class="row">
    <div class="col s12">
        <form method="post" action="">
            {% csrf_token %}
            <button type="submit" class="btn mat360-btn">WithDraw To Sacco Account</button>
        </form>

        <p>This will contain a table of all the transactions being paid out.</p>
    </div>
</div>
</div>
{% endblock %}

templates/sacco_manager/sacco_manager_base.html
<!DOCTYPE html>
<html class="loading" lang="en" data-textdirection="ltr">
  <!-- BEGIN: Head-->
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
    <meta name="description" content="Materialize is a Material Design Admin Template,It's modern, responsive and based on Material Design by Google.">
    <meta name="keywords" content="materialize, admin template, dashboard template, flat admin template, responsive admin template, eCommerce dashboard, analytic dashboard">
    <meta name="author" content="ThemeSelect">

      {% load static %}
    <title>Mat360 | Book a ride while at the comfort of your zone.</title>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
      <link href="" rel="stylesheet">
    <!-- BEGIN: VENDOR CSS-->
    <link rel="stylesheet" type="text/css" href="{% static 'controlled/css/vendors.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'controlled/css/animate.css' %}">
    <!-- END: VENDOR CSS-->
    <!-- BEGIN: Page Level CSS-->
    <link rel="stylesheet" type="text/css" href="{% static 'controlled/css/materialize.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'controlled/css/style.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'controlled/css/dashboard-modern.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'controlled/css/intro.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/gtallk.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/new-main.css' %}">

     <link rel="shortcut icon" href="{% static 'assets/media/logo.ico' %}" type="image/x-icon"/>



  </head>
  <!-- END: Head-->
  <body class="vertical-layout vertical-menu-collapsible page-header-dark vertical-modern-menu preload-transitions 2-columns   " data-open="click" data-menu="vertical-modern-menu" data-col="2-columns">

    <!-- BEGIN: Header-->
    <header class="page-topbar" id="header">
      <div class="navbar navbar-fixed">
        <nav class="navbar-main navbar-color nav-collapsible sideNav-lock navbar-dark gradient-45deg-indigo-purple no-shadow">
          <div class="nav-wrapper">
            <ul class="navbar-list right">
                <li><a class="waves-effect waves-block waves-light notification-button" href="javascript:void(0);" data-target="notifications-dropdown"><i class="material-icons">notifications_none<small class="notification-badge">{{total_alerts }}</small></i></a></li>
              <li><a class="waves-effect waves-block waves-light profile-button" href="javascript:void(0);" data-target="profile-dropdown">{{ user.get_username }}<span>                 
              </span><span class="material-icons">keyboard_arrow_down</span> </a></li>

            </ul>
              <!-- notifications-dropdown-->
            <ul class="dropdown-content" id="notifications-dropdown">
              <li>
                <h6>NOTIFICATIONS<span class="new badge"></span></h6>
              </li>

            </ul>

            <ul class="dropdown-content" id="profile-dropdown">
                <li><a class="grey-text text-darken-1" href=""><i class="material-icons">person_outline</i> Profile</a></li>
                <li><a class="grey-text text-darken-1" href="{% url 'sacco_manager:sacco-settings' %}"><i class="material-icons">engineering_outline</i> Settings</a></li>
                <li><a class="grey-text text-darken-1" href="{% url 'sacco_manager:sacco-finances' %}"><i class="material-icons">money</i> Finances</a></li>

                <li class="divider"></li>
                <li><a class="grey-text text-darken-1" href="{% url 'sacco_manager:logout' %}"><i class="material-icons">keyboard_tab</i> Logout</a></li>
            </ul>
          </div>
        </nav>
      </div>
    </header>
    <!-- END: Header-->

    <aside class="sidenav-main nav-expanded nav-lock nav-collapsible sidenav-light sidenav-active-square">
      <div class="brand-sidebar">
               <p class="center-align">{{ user.sacco_manager.sacco.sacco_name }} Manager</p>
      </div>
      <ul class="sidenav sidenav-collapsible leftside-navigation collapsible sidenav-fixed menu-shadow" id="slide-out" data-menu="menu-navigation" data-collapsible="menu-accordion">
        <li class="active bold"><a class="collapsible-header waves-effect waves-cyan" href="{% url 'sacco_manager:sacco-manager-dashboard' %}" ><i class="material-icons">home</i><span class="menu-title" data-i18n="Dashboard">DashBoard</span></a>
         </li>
          <li class="navigation-header"><a class="navigation-header-text">PORTALS</a><i class="navigation-header-icon material-icons">more_horiz</i>
        </li>
           <li class="bold"><a class="waves-effect waves-cyan " href="{% url 'sacco_manager:register_route' %}"><i class="material-icons">person_outline</i><span class="menu-title" data-i18n="User Profile">ROUTES</span></a></li>
           <li class="bold"><a class="waves-effect waves-cyan " href="{% url 'sacco_manager:new-controller' %}"><i class="material-icons">person_outline</i><span class="menu-title" data-i18n="User Profile">STAGE CONTROLLERS</span></a></li>

      <!--Vehicles-->
           <li class="navigation-header"><a class="navigation-header-text">SACCO VEHICLES</a><i class="navigation-header-icon material-icons">more_horiz</i>
        </li>
         <li class="bold"><a class="waves-effect waves-cyan " href="{% url 'sacco_manager:new-vehicle-registration' %}"><i class="material-icons">person_outline</i><span class="menu-title" data-i18n="User Profile">New Vehicle</span></a></li>
         <li class="bold"><a class="waves-effect waves-cyan " href="{% url 'sacco_manager:our-fleet' %}"><i class="material-icons">airport_shuttle</i><span class="menu-title" data-i18n="User Profile">Our Fleet</span></a></li>

           <!--Finances and statistics-->
           <li class="navigation-header"><a class="navigation-header-text">SACCO ROUTES</a><i class="navigation-header-icon material-icons">more_horiz</i>
        </li>
         <li class="bold"><a class="waves-effect waves-cyan " href="{% url 'sacco_manager:vehicle_stats' %}"><i class="material-icons">person_outline</i><span class="menu-title" data-i18n="User Profile">Vehicle Statistics</span></a></li>


        
      </ul>
      <div class="navigation-background"></div><a class="sidenav-trigger btn-sidenav-toggle btn-floating btn-medium waves-effect waves-light hide-on-large-only" href="#" data-target="slide-out"><i class="material-icons">menu</i></a>
    </aside>
    <!-- END: SideNav-->








    <!-- BEGIN: Page Main-->

    {% block content %}

    {% endblock %}
    <!-- END: Page Main-->









    <!-- BEGIN: Footer-->

    <footer class="page-footer footer footer-static footer-dark gradient-45deg-indigo-purple gradient-shadow navbar-border navbar-shadow">
      <div class="footer-copyright">
        <div class="container"><span>&copy; 2020 <a href="" target="_blank">Mat360</a> All rights reserved.</span><span class="right hide-on-small-only">Design and Developed by <a href="hornafrictech.com">HornAfricTech</a></span></div>
      </div>
    </footer>

    <!-- END: Footer-->
    <script  src="https://code.jquery.com/jquery-3.4.1.min.js"  integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="  crossorigin="anonymous"></script>
    <!-- BEGIN VENDOR JS-->
    <script src="{% static 'controlled/js/vendors.min.js' %}"></script>
    <!-- BEGIN VENDOR JS-->
    <!-- BEGIN PAGE VENDOR JS-->
    <script src="{% static 'controlled/jss/chart.min.js' %}"></script>
    <!-- BEGIN THEME  JS-->
    <script src="{% static 'controlled/js/plugins.min.js' %}"></script>
    <script src="{% static 'controlled/js/search.min.js' %}"></script>
    <script src="{% static 'controlled/js/customizer.min.js' %}"></script>
    <!-- END THEME  JS-->
    <!-- BEGIN PAGE LEVEL JS-->
    <script src="{% static 'controlled/js/dashboard-modern.js' %}"></script>
    <script src="{% static 'controlled/js/intro.min.js' %}"></script>
    <!-- END PAGE LEVEL JS-->
    {% block javascript %}
    {% endblock %}
  </body>
</html>

templates/sacco_manager/sacco_profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>$Title$</title>
</head>
<body>
$END$
</body>
</html>